; SPDX-FileType: SOURCE
; SPDX-FileCopyrightText: Copyright (C) 2026 Volkert de Buisonjé
; SPDX-FileContributor: Generated by Claude (Anthropic), reviewed by Volkert de Buisonjé
; SPDX-License-Identifier: Apache-2.0
;
; Serial Port Debug Output (polled)
;
; Lightweight routines for printing diagnostic information to a serial
; port. The port's base I/O address is read from the BIOS Data Area
; (BDA), which stores COM1-COM4 base addresses as consecutive words
; starting at linear address 0x400. Intended for use with QEMU's
; -serial option. Uses polled I/O (busy-wait on THRE), no IRQ needed.
;
; All routines preserve the registers they use.
;
; To enable, define DEBUG_SERIAL before including this file.
; When DEBUG_SERIAL is not defined, this file produces no code.
;
; Optionally define DEBUG_SERIAL_PORT to select which COM port to use
; (1-4). Defaults to 1 (COM1) if not defined.

IFDEF DEBUG_SERIAL

IFNDEF DBGSER_ASM_INCLUDED
DBGSER_ASM_INCLUDED EQU 1

IFNDEF DEBUG_SERIAL_PORT
DEBUG_SERIAL_PORT EQU   1               ;default to COM1
ENDIF

;BDA stores COM1-COM4 base I/O addresses as consecutive words at 0x400
BDA_COM_BASE    EQU     400h + (DEBUG_SERIAL_PORT - 1) * 2

LSR_OFFSET      EQU     5               ;Line Status Register offset from port base
LSR_THRE        EQU     20h             ;Transmitter Holding Register Empty (bit 5)

;----------------------------------------------------------------------------
; dbg_char -- Output a single character to the debug serial port
;
; Entry: AL = character to output
; Exit:  All registers preserved
;
dbg_char PROC NEAR
                push    eax
                push    edx

                mov     ah, al                  ;save character in AH
                movzx   edx, WORD PTR ds:[BDA_COM_BASE]
                or      dx, dx
                jz      __no_port               ;COM port not present in BDA

                push    edx                     ;save base address
                add     dx, LSR_OFFSET          ;Line Status Register
@@:             in      al, dx                  ;wait for transmitter ready
                test    al, LSR_THRE
                jz      @b

                pop     edx                     ;restore base address
                mov     al, ah                  ;restore character
                out     dx, al

__no_port:      pop     edx
                pop     eax
                ret
dbg_char ENDP

;----------------------------------------------------------------------------
; dbg_hex8 -- Output a byte as two hex digits to COM1
;
; Entry: AL = byte to output
; Exit:  All registers preserved
;
dbg_hex8 PROC NEAR
                push    eax
                push    ecx

                mov     cl, al                  ;save original byte
                shr     al, 4                   ;high nibble
                call    __nibble
                mov     al, cl                  ;low nibble
                and     al, 0Fh
                call    __nibble

                pop     ecx
                pop     eax
                ret

__nibble:       add     al, '0'
                cmp     al, '9'
                jbe     @f
                add     al, 7                   ;'A'-'9'-1 = 7
@@:             call    dbg_char
                ret
dbg_hex8 ENDP

;----------------------------------------------------------------------------
; dbg_hex16 -- Output a 16-bit value as four hex digits to COM1
;
; Entry: AX = value to output
; Exit:  All registers preserved
;
dbg_hex16 PROC NEAR
                push    eax

                xchg    al, ah                  ;high byte first
                call    dbg_hex8
                xchg    al, ah                  ;low byte
                call    dbg_hex8

                pop     eax
                ret
dbg_hex16 ENDP

;----------------------------------------------------------------------------
; dbg_hex32 -- Output a 32-bit value as eight hex digits to COM1
;
; Entry: EAX = value to output
; Exit:  All registers preserved
;
dbg_hex32 PROC NEAR
                push    eax

                rol     eax, 8                  ;byte 3 (MSB)
                call    dbg_hex8
                rol     eax, 8                  ;byte 2
                call    dbg_hex8
                rol     eax, 8                  ;byte 1
                call    dbg_hex8
                rol     eax, 8                  ;byte 0 (LSB, back to original)
                call    dbg_hex8

                pop     eax
                ret
dbg_hex32 ENDP

;----------------------------------------------------------------------------
; dbg_str -- Output a null-terminated string to COM1
;
; Entry: ESI = pointer to null-terminated string
; Exit:  All registers preserved
;
dbg_str PROC NEAR
                push    eax
                push    esi

@@:             lodsb
                or      al, al
                jz      @f
                call    dbg_char
                jmp     @b

@@:             pop     esi
                pop     eax
                ret
dbg_str ENDP

;----------------------------------------------------------------------------
; dbg_crlf -- Output a CR+LF to COM1
;
; Entry: None
; Exit:  All registers preserved
;
dbg_crlf PROC NEAR
                push    eax
                mov     al, 0Dh
                call    dbg_char
                mov     al, 0Ah
                call    dbg_char
                pop     eax
                ret
dbg_crlf ENDP

;----------------------------------------------------------------------------
; dbg_label_hex16 -- Output "label: XXXX\r\n" to COM1
;
; Entry: ESI = pointer to label string, AX = 16-bit value
; Exit:  All registers preserved
;
dbg_label_hex16 PROC NEAR
                call    dbg_str
                call    dbg_hex16
                call    dbg_crlf
                ret
dbg_label_hex16 ENDP

;----------------------------------------------------------------------------
; dbg_label_hex32 -- Output "label: XXXXXXXX\r\n" to COM1
;
; Entry: ESI = pointer to label string, EAX = 32-bit value
; Exit:  All registers preserved
;
dbg_label_hex32 PROC NEAR
                call    dbg_str
                call    dbg_hex32
                call    dbg_crlf
                ret
dbg_label_hex32 ENDP

ENDIF ; DBGSER_ASM_INCLUDED
ENDIF ; DEBUG_SERIAL
