; SPDX-FileType: SOURCE
; SPDX-FileCopyrightText: Copyright (C) 2026 Volkert de Buisonjé
; SPDX-FileContributor: Generated by Claude (Anthropic), reviewed by Volkert de Buisonjé
; SPDX-License-Identifier: Apache-2.0
;
; DPMI Memory Helper Routines
;
; Generic DPMI memory allocation and deallocation routines for use by
; AIL/32 drivers that need dynamically allocated, DMA-safe memory
; (e.g. staging buffers for format conversion).
;
; Prerequisites: The including file must define the following variables
; before this file is included. The routines take a slot index in EBX
; and index into these arrays; the caller must ensure the arrays are
; large enough for all indices used.
;
;   stg_addr      dd N dup (0)   ; linear address (0 = not allocated)
;   stg_size      dd N dup (0)   ; allocated size in bytes
;   stg_handle_hi dw N dup (0)   ; DPMI handle high word (SI from INT 31h/0501h)
;   stg_handle_lo dw N dup (0)   ; DPMI handle low word (DI from INT 31h/0501h)
;
; The caller is responsible for deciding when it is safe to free and
; reallocate a slot (e.g. checking that DMA is not reading from it).

IFNDEF DPMI_ASM_INCLUDED
DPMI_ASM_INCLUDED EQU 1

;----------------------------------------------------------------------------
; dpmi_alloc_staging -- Allocate a memory block via DPMI and lock it
;
; The target slot (stg_addr[ebx*4]) must be 0 (not in use). If the slot
; is already allocated, the caller must free it first via dpmi_free_staging.
;
; Entry: EBX = slot index, ECX = required size in bytes
; Exit:  CF clear on success (stg_addr/stg_size/stg_handle updated)
;        CF set on failure (slot unchanged)
; Destroys: EAX, ECX, EDX (other regs preserved via pushes)
;
dpmi_alloc_staging PROC NEAR
                push esi
                push edi
                push ebx

                ;DPMI Allocate Memory Block (INT 31h AX=0501h)
                ;BX:CX = size in bytes
                push    ebx                     ;save slot index
                push    ecx                     ;save requested size (INT 31h returns
                                                ;the handle in SI:DI, clobbering EDI)
                mov     eax, ecx
                shr     eax, 16
                mov     ebx, eax                ;BX = high word of size
                and     ecx, 0FFFFh             ;CX = low word of size
                mov     ax, 0501h
                int     31h
                pop     edi                     ;EDI = requested size (safe from INT 31h)
                pop     eax                     ;restore slot index into EAX
                jc      __fail

                ;BX:CX = linear address, SI:DI = handle (DI was clobbered
                ;by INT 31h, but we restored the size into EDI from the stack)
                mov     stg_handle_hi[eax*2], si
                mov     stg_handle_lo[eax*2], di
                shl     ebx, 16
                or      ebx, ecx                ;EBX = full linear address
                mov     stg_addr[eax*4], ebx
                mov     stg_size[eax*4], edi

                ;DPMI Lock Linear Region (INT 31h AX=0600h)
                ;BX:CX = linear address, SI:DI = size
                mov     ecx, ebx
                shr     ebx, 16                 ;BX = high word of address
                and     ecx, 0FFFFh             ;CX = low word of address
                mov     esi, edi
                shr     esi, 16                 ;SI = high word of size
                and     edi, 0FFFFh             ;DI = low word of size
                mov     ax, 0600h
                int     31h
                ;Ignore lock failure -- under DOS/4GW there is no paging,
                ;so the lock is a no-op. On other DPMI hosts it may fail
                ;for lack of lockable memory, but the allocation itself
                ;succeeded and will work for DMA in practice.

                pop     ebx
                pop     edi
                pop     esi
                clc
                ret

__fail:         pop     ebx
                pop     edi
                pop     esi
                stc
                ret
dpmi_alloc_staging ENDP

;----------------------------------------------------------------------------
; dpmi_free_staging -- Unlock and free a memory block via DPMI
;
; If the slot is not allocated (stg_addr[ebx*4] == 0), this is a no-op.
;
; Entry: EBX = slot index
; Exit:  stg_addr[ebx*4] and stg_size[ebx*4] set to 0
; Destroys: EAX
;
dpmi_free_staging PROC NEAR
                push    esi
                push    edi

                cmp     stg_addr[ebx*4], 0
                je      __done

                ;DPMI Unlock Linear Region (INT 31h AX=0601h)
                ;BX:CX = linear address, SI:DI = size
                push    ebx                     ;save slot index
                mov     eax, stg_size[ebx*4]
                mov     edi, eax
                and     edi, 0FFFFh             ;DI = low word of size
                shr     eax, 16
                mov     esi, eax                ;SI = high word of size
                mov     eax, stg_addr[ebx*4]
                mov     ecx, eax
                and     ecx, 0FFFFh             ;CX = low word of address
                shr     eax, 16
                mov     ebx, eax                ;BX = high word of address
                mov     ax, 0601h
                int     31h                     ;ignore errors
                pop     ebx                     ;restore slot index

                ;DPMI Free Memory Block (INT 31h AX=0502h)
                ;SI:DI = handle
                push    ebx
                mov     si, stg_handle_hi[ebx*2]
                mov     di, stg_handle_lo[ebx*2]
                mov     ax, 0502h
                int     31h
                pop     ebx

                mov     stg_addr[ebx*4], 0
                mov     stg_size[ebx*4], 0

__done:         pop     edi
                pop     esi
                ret
dpmi_free_staging ENDP

;----------------------------------------------------------------------------
; dpmi_alloc_conv -- Allocate a conventional memory block via DPMI
;
; Conventional memory (below 1 MB) is identity-mapped under DOS/4GW:
; linear address == physical address. This makes it suitable for DMA
; buffers where the PCI bus master engine needs a physical address.
;
; Entry: EBX = slot index, ECX = required size in bytes
; Exit:  CF clear on success (stg_addr/stg_size/stg_handle_lo updated)
;        CF set on failure (slot unchanged)
; Destroys: EAX, ECX, EDX (other regs preserved via pushes)
;
dpmi_alloc_conv PROC NEAR
                push    edi
                push    ebx

                mov     edi, ecx                ;save requested size

                ;DPMI Allocate DOS Memory Block (INT 31h AX=0100h)
                ;BX = number of 16-byte paragraphs to allocate
                add     ecx, 15
                shr     ecx, 4                  ;round up to paragraphs

                push    ebx                     ;save slot index
                mov     ebx, ecx                ;BX = paragraphs
                mov     ax, 0100h
                int     31h
                pop     ebx                     ;restore slot index
                jc      __cfail

                ;AX = real-mode segment, DX = protected-mode selector
                mov     stg_handle_lo[ebx*2], dx ;save selector for freeing
                movzx   eax, ax
                shl     eax, 4                  ;linear addr = segment * 16
                mov     stg_addr[ebx*4], eax
                mov     stg_size[ebx*4], edi

                pop     ebx
                pop     edi
                clc
                ret

__cfail:        pop     ebx
                pop     edi
                stc
                ret
dpmi_alloc_conv ENDP

;----------------------------------------------------------------------------
; dpmi_free_conv -- Free a conventional memory block via DPMI
;
; If the slot is not allocated (stg_addr[ebx*4] == 0), this is a no-op.
;
; Entry: EBX = slot index
; Exit:  stg_addr[ebx*4] and stg_size[ebx*4] set to 0
; Destroys: EAX, EDX
;
dpmi_free_conv PROC NEAR
                cmp     stg_addr[ebx*4], 0
                je      __cdone

                ;DPMI Free DOS Memory Block (INT 31h AX=0101h)
                ;DX = selector (from INT 31h AX=0100h)
                mov     dx, stg_handle_lo[ebx*2]
                mov     ax, 0101h
                int     31h                     ;ignore errors

                mov     stg_addr[ebx*4], 0
                mov     stg_size[ebx*4], 0

__cdone:        ret
dpmi_free_conv ENDP

ENDIF ; DPMI_ASM_INCLUDED
