; SPDX-FileType: SOURCE
; SPDX-FileCopyrightText: Copyright (C) 2026 Volkert de Buisonje
; SPDX-FileContributor: Adapted from dmasnd32.asm (AIL/32 by John Miles / Miles Design, Inc.)
; SPDX-FileContributor: Generated by Claude (Anthropic), reviewed by Volkert de Buisonje
; SPDX-License-Identifier: Apache-2.0
;
; Panning Volume Calculation
;
; Computes separate left and right volumes from a master volume and a
; pan-pot position using a 128-entry lookup table. The table ramps
; linearly from 0 to 127 over indices 0-63, then holds at 127 for
; indices 64-127. This produces the standard AIL/32 "constant power
; approximation" pan law shared across all stereo drivers.
;
; Prerequisites: The including file must define the following variables
; before this file is included:
;
;   main_volume   dd ?   ; AIL volume 0-127
;   panpot_val    dd ?   ; AIL pan 0-127 (0=hard right, 64=center, 127=hard left)

IFNDEF PAN_ASM_INCLUDED
PAN_ASM_INCLUDED EQU 1

;----------------------------------------------------------------------------
; pan_graph -- Panning scale-factor lookup table (128 bytes)
;
; Index 0-63: linear ramp 0, 2, 4, ..., 126, 127
; Index 64-127: constant 127
;
; Used by calc_pan_volumes to convert a pan position into a per-channel
; scale factor.
;----------------------------------------------------------------------------

pan_graph       db 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
                db 32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
                db 64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94
                db 96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,127
                db 127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127
                db 127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127
                db 127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127
                db 127,127,127,127,127,127,127,127,127,127,127,127,127,127,127,127

;----------------------------------------------------------------------------
; calc_pan_volumes -- Compute panned left/right volumes
;
; Reads main_volume and panpot_val globals. Produces left and right
; volume values in the range 0-16129 (127 * 127). These are suitable
; for further scaling into device-specific attenuation fields.
;
; Pan mapping:
;   panpot_val = 0   -> hard right (left volume = 0)
;   panpot_val = 64  -> center     (left = right = main_volume * 127)
;   panpot_val = 127 -> hard left  (right volume = 0)
;
; Entry: main_volume and panpot_val must be set
; Exit:  ESI = left volume (0-16129)
;        EDI = right volume (0-16129)
; Destroys: EAX
;----------------------------------------------------------------------------

calc_pan_volumes PROC NEAR
                mov     esi, 127
                sub     esi, panpot_val
                movzx   eax, pan_graph[esi]     ;right scale factor
                mul     BYTE PTR main_volume    ;AX = right vol 0-16129
                mov     edi, eax                ;EDI = right volume

                mov     esi, panpot_val
                movzx   eax, pan_graph[esi]     ;left scale factor
                mul     BYTE PTR main_volume    ;AX = left vol 0-16129
                mov     esi, eax                ;ESI = left volume
                ret
calc_pan_volumes ENDP

ENDIF ; PAN_ASM_INCLUDED
