; SPDX-FileType: SOURCE
; SPDX-FileCopyrightText: Copyright (C) 2026 Volkert de Buisonje
; SPDX-FileContributor: Generated by Claude (Anthropic), reviewed by Volkert de Buisonje
; SPDX-License-Identifier: Apache-2.0
;
; Physical Address Translation for PCI Bus Master DMA
;
; PCI DMA engines operate on physical (bus) memory addresses, but DPMI
; applications in protected mode work with linear (virtual) addresses.
; Under paging, linear != physical for extended memory allocations.
; This module detects the best available method to translate linear
; addresses to physical addresses, with a multi-tier fallback:
;
;   1. Identity mapping probe -- cheap test; works when the DPMI host
;      does not remap extended memory (e.g. DOS/4GW without EMM386)
;   2. Ring 0 page table walk -- works under DOS extenders that run
;      applications in ring 0 (e.g. DOS/32A); reads CR3 and walks
;      the page directory/table to find the physical page frame
;   3. Virtual DMA Services (VDS) -- INT 4Bh API provided by EMM386,
;      QEMM, JEMMEX; locks a DMA region and returns its physical address
;   4. PHYSADDR_NONE -- no translation available; caller must fall back
;      to conventional memory (below 1 MB) where linear == physical
;
; Public API:
;   physaddr_detect       -- detect best method (call once from init_driver)
;   physaddr_translate    -- translate linear -> physical
;   physaddr_release_lock -- release a VDS lock (no-op for other methods)
;   physaddr_shutdown     -- free internal resources (call from shutdown_driver)

IFNDEF PHYSADDR_ASM_INCLUDED
PHYSADDR_ASM_INCLUDED EQU 1

IFDEF DEBUG_SERIAL
                INCLUDE util/dbgser.asm
ENDIF

;--- Method constants (stored in physaddr_method) ---
PHYSADDR_IDENTITY EQU 1         ;Linear == physical (identity-mapped)
PHYSADDR_RING0    EQU 2         ;Ring 0 page table walk
PHYSADDR_VDS      EQU 3         ;Virtual DMA Services (INT 4Bh)
PHYSADDR_NONE     EQU 4         ;No translation; caller must use conventional memory

;--- Internal state ---
physaddr_method   dd 0           ;Detected method (0 = not yet initialized)

;Ring 0 page table walk state
r0_pdir_phys    dd 0             ;Physical address of page directory (from CR3)
r0_pdir_lin     dd 0             ;Linear mapping of page directory (DPMI 0800h)
r0_ptab_phys    dd 0             ;Cached page table physical address
r0_ptab_lin     dd 0             ;Cached page table linear mapping

;VDS state -- DDS (DMA Descriptor Structure) must reside in conventional
;memory because VDS is a real-mode API called via DPMI INT simulation
vds_dds_lin     dd 0             ;Linear address of 16-byte DDS
vds_dds_seg     dw 0             ;Real-mode segment of DDS
vds_dds_sel     dw 0             ;DPMI selector for freeing the block

;Static DPMI Real-Mode Call Structure (RMCS) for VDS calls.
;50 bytes (32h), allocated as 52 (34h) for dword alignment.
vds_rmcs        db 34h dup (0)

;--- Magic values for identity mapping probe ---
PHYSADDR_MAGIC_1 EQU 0DEAD1CEDh
PHYSADDR_MAGIC_2 EQU 0C0FFEE42h

;--- VDS DDS field offsets ---
DDS_SIZE        EQU 0            ;DWORD: region size in bytes
DDS_LINEAR      EQU 4            ;DWORD: linear address of region
DDS_SEG         EQU 8            ;WORD: segment/selector (0 for flat model)
DDS_BUFID       EQU 0Ah          ;WORD: buffer ID (returned by Lock)
DDS_PHYS        EQU 0Ch          ;DWORD: physical address (returned by Lock)

;--- DPMI Real-Mode Call Structure field offsets ---
RMCS_EDI        EQU 0
RMCS_ESI        EQU 4
RMCS_EBP        EQU 8
RMCS_RSV        EQU 0Ch
RMCS_EBX        EQU 10h
RMCS_EDX        EQU 14h
RMCS_ECX        EQU 18h
RMCS_EAX        EQU 1Ch
RMCS_FLAGS      EQU 20h
RMCS_ES         EQU 22h
RMCS_DS         EQU 24h
RMCS_FS         EQU 26h
RMCS_GS         EQU 28h
RMCS_IP         EQU 2Ah
RMCS_CS         EQU 2Ch
RMCS_SP         EQU 2Eh
RMCS_SS         EQU 30h
RMCS_ALLOC      EQU 34h          ;Allocation size (dword-aligned)

IFDEF DEBUG_SERIAL
dbg_s_pa_init   db '--- physaddr_detect',13,10,0
dbg_s_pa_probe  db 'Probe identity... ',0
dbg_s_pa_ring0  db 'Check ring 0... ',0
dbg_s_pa_cpl    db 'CPL=',0
dbg_s_pa_cr3    db 'CR3=',0
dbg_s_pa_pdir   db 'pdir_lin=',0
dbg_s_pa_vds    db 'Check VDS... ',0
dbg_s_pa_none   db 'No method -> PHYSADDR_NONE',13,10,0
dbg_s_pa_ok     db 'OK',13,10,0
dbg_s_pa_fail   db 'FAIL',13,10,0
dbg_s_pa_sel    db 'physaddr_method=',0
dbg_s_pa_get    db 'phys: lin=',0
dbg_s_pa_arrow  db ' phys=',0
ENDIF

;============================================================================
; physaddr_detect -- Detect the best physical address translation method
;
; Probes methods in order of preference: identity mapping, ring 0 page
; table walk, VDS. Sets physaddr_method to the first working method, or
; PHYSADDR_NONE if none is available.
;
; Entry: None (call once from init_driver)
; Exit:  CF clear if a translation method was found (physaddr_method 1-3)
;        CF set if no method found (physaddr_method = PHYSADDR_NONE)
; Destroys: EAX, ECX, EDX
;
physaddr_detect PROC NEAR
                push    ebx
                push    esi
                push    edi

IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_init
                call    dbg_str
ENDIF

                ;--- Tier 1: Identity mapping probe ---
IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_probe
                call    dbg_str
ENDIF
                call    __probe_identity
                jnc     __pi_identity

IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_fail
                call    dbg_str
ENDIF

                ;--- Tier 2: Ring 0 page table walk ---
IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_ring0
                call    dbg_str
ENDIF
                call    __probe_ring0
                jnc     __pi_ring0

IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_fail
                call    dbg_str
ENDIF

                ;--- Tier 3: Virtual DMA Services ---
IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_vds
                call    dbg_str
ENDIF
                call    __probe_vds
                jnc     __pi_vds

IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_fail
                call    dbg_str
ENDIF

                ;--- No method available ---
                mov     physaddr_method, PHYSADDR_NONE

IFDEF DEBUG_SERIAL
                mov     esi, OFFSET dbg_s_pa_none
                call    dbg_str
ENDIF
                pop     edi
                pop     esi
                pop     ebx
                stc
                ret

__pi_identity:  mov     physaddr_method, PHYSADDR_IDENTITY
                jmp     __pi_ok

__pi_ring0:     mov     physaddr_method, PHYSADDR_RING0
                jmp     __pi_ok

__pi_vds:       mov     physaddr_method, PHYSADDR_VDS

__pi_ok:
IFDEF DEBUG_SERIAL
                push    eax
                mov     esi, OFFSET dbg_s_pa_ok
                call    dbg_str
                mov     esi, OFFSET dbg_s_pa_sel
                mov     eax, physaddr_method
                call    dbg_label_hex32
                pop     eax
ENDIF
                pop     edi
                pop     esi
                pop     ebx
                clc
                ret
physaddr_detect ENDP

;============================================================================
; __probe_identity -- Test whether DPMI allocations are identity-mapped
;
; Allocates a 4 KB test block via DPMI, writes a magic pattern, then
; uses DPMI Map Physical Address (INT 31h AX=0800h) to create a second
; linear mapping at the test block's linear address (interpreted as a
; physical address). If the magic appears through the second mapping,
; linear == physical. Two-way verification prevents false positives from
; coincidental memory contents.
;
; Exit: CF clear if identity-mapped, CF set if not
; Destroys: EAX, EBX, ECX, EDX, ESI, EDI
;
__probe_identity PROC NEAR
                ;Allocate a 4 KB test block via DPMI Allocate Memory Block
                ;(INT 31h AX=0501h). BX:CX = size in bytes.
                xor     ebx, ebx
                mov     ecx, 1000h          ;4096 bytes
                mov     ax, 0501h
                int     31h
                jc      __id_no_alloc

                ;BX:CX = linear address of allocated block
                ;SI:DI = DPMI memory handle (needed for freeing)
                push    esi                 ;save handle high word
                push    edi                 ;save handle low word
                shl     ebx, 16
                or      ebx, ecx            ;EBX = full linear address

                ;Write first magic pattern at the start of the test block
                mov     DWORD PTR [ebx], PHYSADDR_MAGIC_1

                ;Use DPMI Map Physical Address (INT 31h AX=0800h) to map
                ;the test block's linear address as if it were a physical
                ;address. If identity-mapped, this creates a second view
                ;of the same physical page.
                ;BX:CX = "physical" address to map, SI:DI = size
                push    ebx                 ;save original linear address
                mov     ecx, ebx
                shr     ebx, 16             ;BX = high word of address
                and     ecx, 0FFFFh         ;CX = low word of address
                xor     esi, esi
                mov     edi, 1000h          ;SI:DI = 4096 bytes
                mov     ax, 0800h
                int     31h
                pop     edx                 ;EDX = original linear address
                jc      __id_no_map

                ;BX:CX = new linear mapping of the "physical" address
                shl     ebx, 16
                or      ebx, ecx            ;EBX = mapped linear address

                ;--- Forward check: read magic 1 through the mapped view ---
                cmp     DWORD PTR [ebx], PHYSADDR_MAGIC_1
                jne     __id_mismatch

                ;--- Reverse check: write magic 2 through mapping,
                ;    read back through original pointer ---
                mov     DWORD PTR [ebx], PHYSADDR_MAGIC_2
                cmp     DWORD PTR [edx], PHYSADDR_MAGIC_2
                jne     __id_mismatch

                ;Two-way verification passed -- identity mapping confirmed
                ;Free physical address mapping (DPMI INT 31h AX=0801h)
                mov     ecx, ebx
                shr     ebx, 16
                and     ecx, 0FFFFh
                mov     ax, 0801h
                int     31h                 ;ignore errors

                ;Free test memory block (DPMI INT 31h AX=0502h, SI:DI = handle)
                pop     edi
                pop     esi
                mov     ax, 0502h
                int     31h

                clc                         ;success: identity-mapped
                ret

__id_mismatch:  ;Verification failed -- unmap, then fall through to free
                mov     ecx, ebx
                shr     ebx, 16
                and     ecx, 0FFFFh
                mov     ax, 0801h
                int     31h                 ;ignore errors

__id_no_map:    ;Free the test block (handle is on the stack)
                pop     edi
                pop     esi
                mov     ax, 0502h
                int     31h

__id_no_alloc:  stc                         ;probe failed
                ret
__probe_identity ENDP

;============================================================================
; __probe_ring0 -- Check if running at ring 0; set up page table walk
;
; Checks the Current Privilege Level (CPL) from the CS selector's RPL
; field. If ring 0, reads CR3 (Page Directory Base Register) and maps
; the page directory into linear address space via DPMI 0800h. If paging
; is not enabled (CR0.PG = 0), returns success without mapping (the
; physaddr_translate ring 0 path will return addresses unchanged).
;
; Exit: CF clear if ring 0 (ready for page table walk or no paging)
;       CF set if ring 3 or page directory mapping failed
; Destroys: EAX, EBX, ECX, EDX, ESI, EDI
;
__probe_ring0 PROC NEAR
                ;Check Current Privilege Level -- the RPL field (bits 1:0)
                ;of the CS selector equals the CPL for the code segment
                mov     ax, cs
                and     eax, 3              ;isolate CPL

IFDEF DEBUG_SERIAL
                push    eax
                push    esi
                mov     esi, OFFSET dbg_s_pa_cpl
                call    dbg_str
                call    dbg_hex8
                call    dbg_crlf
                pop     esi
                pop     eax
ENDIF
                jnz     __r0_fail           ;CPL != 0, not ring 0

                ;At ring 0 -- check if paging is enabled via CR0 bit 31
                ;(Page Enable). Reading CR0 is a privileged instruction.
                mov     eax, cr0
                test    eax, 80000000h      ;PG (Page Enable) bit
                jz      __r0_no_paging

                ;Paging enabled -- read CR3 (Page Directory Base Register)
                ;to find the physical address of the page directory
                mov     eax, cr3
                and     eax, 0FFFFF000h     ;mask PCID/flags in low 12 bits
                mov     r0_pdir_phys, eax

IFDEF DEBUG_SERIAL
                push    esi
                mov     esi, OFFSET dbg_s_pa_cr3
                call    dbg_label_hex32
                pop     esi
ENDIF

                ;Map the page directory into our linear address space via
                ;DPMI Map Physical Address (INT 31h AX=0800h) so we can
                ;read Page Directory Entries (PDEs) during address translation
                mov     ecx, eax
                shr     eax, 16
                mov     ebx, eax            ;BX = high word of physical address
                and     ecx, 0FFFFh         ;CX = low word
                xor     esi, esi
                mov     edi, 1000h          ;SI:DI = 4096 bytes (one 4 KB page)
                mov     ax, 0800h
                int     31h
                jc      __r0_fail

                ;BX:CX = linear address of mapped page directory
                shl     ebx, 16
                or      ebx, ecx
                mov     r0_pdir_lin, ebx

IFDEF DEBUG_SERIAL
                push    eax
                push    esi
                mov     eax, ebx
                mov     esi, OFFSET dbg_s_pa_pdir
                call    dbg_label_hex32
                pop     esi
                pop     eax
ENDIF
                clc
                ret

__r0_no_paging:
                ;Ring 0 with paging disabled -- linear == physical.
                ;physaddr_translate checks CR0.PG and returns unchanged.
                clc
                ret

__r0_fail:      stc
                ret
__probe_ring0 ENDP

;============================================================================
; __probe_vds -- Check if Virtual DMA Services (VDS) are available
;
; VDS presence is indicated by bit 5 of the byte at linear address
; 0x47B (BIOS Data Area 40:7Bh). If present, allocates a 16-byte DDS
; (DMA Descriptor Structure) in conventional memory for real-mode
; INT 4Bh calls.
;
; Exit: CF clear if VDS available and DDS allocated
;       CF set if VDS not present or allocation failed
; Destroys: EAX, EBX, ECX, EDX
;
__probe_vds PROC NEAR
                ;Check VDS installed flag in BIOS Data Area
                ;Byte at linear 0x47B, bit 5 = VDS present
                test    BYTE PTR ds:[47Bh], 20h
                jz      __vds_absent

                ;Allocate conventional memory for the DDS (16 bytes = 1
                ;paragraph). DPMI Allocate DOS Memory Block (INT 31h
                ;AX=0100h), BX = number of 16-byte paragraphs.
                mov     ebx, 1              ;1 paragraph = 16 bytes
                mov     ax, 0100h
                int     31h
                jc      __vds_absent

                ;AX = real-mode segment, DX = protected-mode selector
                mov     vds_dds_seg, ax
                mov     vds_dds_sel, dx
                movzx   eax, ax
                shl     eax, 4              ;linear address = segment * 16
                mov     vds_dds_lin, eax

                clc
                ret

__vds_absent:   stc
                ret
__probe_vds ENDP

;============================================================================
; physaddr_translate -- Translate a linear address to a physical address
;
; Uses the method detected by physaddr_detect. For PHYSADDR_IDENTITY,
; returns the linear address unchanged. For PHYSADDR_RING0, walks the
; x86 page tables. For PHYSADDR_VDS, calls VDS Lock DMA Region
; (INT 4Bh AX=8103h). For PHYSADDR_NONE, returns CF set.
;
; Entry: EAX = linear address, ECX = region size in bytes
; Exit:  EAX = physical address (valid only if CF clear)
;        EDX = lock handle (nonzero for VDS, 0 otherwise)
;        CF clear on success, CF set on failure
; Destroys: EAX, EDX
;
physaddr_translate PROC NEAR
                push    ebx
                push    ecx
                push    esi
                push    edi
                xor     edx, edx            ;default lock handle = 0

IFDEF DEBUG_SERIAL
                push    eax
                push    esi
                mov     esi, OFFSET dbg_s_pa_get
                call    dbg_str
                call    dbg_hex32
                pop     esi
                pop     eax
ENDIF

                cmp     physaddr_method, PHYSADDR_IDENTITY
                je      __pg_ok             ;EAX unchanged, EDX=0

                cmp     physaddr_method, PHYSADDR_RING0
                je      __pg_ring0

                cmp     physaddr_method, PHYSADDR_VDS
                je      __pg_vds

                jmp     __pg_fail           ;PHYSADDR_NONE or uninitialized

                ;--- Ring 0: page table walk ---
__pg_ring0:
                ;If paging is not enabled, linear == physical
                mov     ebx, cr0
                test    ebx, 80000000h      ;CR0.PG (Page Enable) bit
                jz      __pg_ok             ;no paging, EAX is physical

                ;Page Directory Entry (PDE) index = linear address bits 31:22
                mov     ebx, eax
                shr     ebx, 22             ;EBX = PDE index (0-1023)

                ;Read PDE from mapped page directory
                mov     edx, r0_pdir_lin
                mov     edx, DWORD PTR [edx + ebx*4]

                ;Check PDE Present bit (bit 0)
                test    edx, 1
                jz      __pg_fail           ;page not present

                ;Check Page Size (PS) bit (bit 7) for 4 MB PSE pages
                test    edx, 80h
                jnz     __r0_4mb

                ;--- 4 KB page: read Page Table Entry (PTE) ---
                ;Page table physical address = PDE bits 31:12
                and     edx, 0FFFFF000h

                ;Check if this page table is already cached from a
                ;previous lookup (staging buffers are often in the same
                ;4 MB region, so the same page table is reused)
                cmp     edx, r0_ptab_phys
                je      __r0_cached

                ;Different page table -- unmap the old cached one if any
                cmp     r0_ptab_lin, 0
                je      __r0_no_old

                push    eax
                push    edx
                mov     ecx, r0_ptab_lin
                mov     ebx, ecx
                shr     ebx, 16
                and     ecx, 0FFFFh
                mov     ax, 0801h           ;DPMI Free Physical Address Mapping
                int     31h
                mov     r0_ptab_lin, 0
                pop     edx
                pop     eax

__r0_no_old:    ;Map new page table via DPMI Map Physical Address
                ;(INT 31h AX=0800h). BX:CX = physical, SI:DI = size.
                mov     r0_ptab_phys, edx
                push    eax                 ;save original linear address
                mov     ecx, edx
                shr     edx, 16
                mov     ebx, edx            ;BX = high word of physical
                and     ecx, 0FFFFh         ;CX = low word
                xor     esi, esi
                mov     edi, 1000h          ;SI:DI = 4096 bytes
                mov     ax, 0800h
                int     31h
                pop     eax
                jc      __pg_fail

                shl     ebx, 16
                or      ebx, ecx
                mov     r0_ptab_lin, ebx    ;cache the new mapping
                jmp     __r0_pte

__r0_cached:    mov     ebx, r0_ptab_lin

__r0_pte:       ;PTE index = linear address bits 21:12
                mov     edx, eax
                shr     edx, 12
                and     edx, 3FFh           ;EDX = PTE index (0-1023)

                ;Read PTE from mapped page table
                mov     edx, DWORD PTR [ebx + edx*4]

                ;Check PTE Present bit (bit 0)
                test    edx, 1
                jz      __pg_fail

                ;Physical address = PTE frame (bits 31:12) | page offset
                ;(linear address bits 11:0)
                and     edx, 0FFFFF000h     ;physical page frame
                mov     ebx, eax
                and     ebx, 0FFFh          ;offset within 4 KB page
                or      edx, ebx
                mov     eax, edx            ;EAX = physical address
                xor     edx, edx            ;lock handle = 0
                jmp     __pg_ok

                ;--- 4 MB PSE page ---
__r0_4mb:       ;Physical = PDE frame (bits 31:22) | offset (bits 21:0)
                and     edx, 0FFC00000h     ;4 MB page frame
                mov     ebx, eax
                and     ebx, 003FFFFFh      ;offset within 4 MB page
                or      edx, ebx
                mov     eax, edx
                xor     edx, edx
                jmp     __pg_ok

                ;--- VDS: Lock DMA Region via INT 4Bh ---
__pg_vds:
                ;Fill DDS (DMA Descriptor Structure) in conventional memory
                mov     ebx, vds_dds_lin
                mov     DWORD PTR [ebx + DDS_SIZE], ecx
                mov     DWORD PTR [ebx + DDS_LINEAR], eax
                mov     WORD PTR [ebx + DDS_SEG], 0
                mov     WORD PTR [ebx + DDS_BUFID], 0
                mov     DWORD PTR [ebx + DDS_PHYS], 0

                ;Zero the static RMCS (Real-Mode Call Structure)
                push    eax
                push    ecx
                mov     edi, OFFSET vds_rmcs
                mov     ecx, RMCS_ALLOC / 4 ;13 dwords
                xor     eax, eax
                rep     stosd
                pop     ecx
                pop     eax

                ;Fill RMCS for VDS Lock DMA Region (INT 4Bh AX=8103h)
                mov     DWORD PTR vds_rmcs[RMCS_EAX], 8103h
                ;RMCS_EDX = 0 (flags: enable auto-remap if needed)
                ;RMCS_EDI = 0 (offset 0 within DDS segment)
                mov     ax, vds_dds_seg
                mov     WORD PTR vds_rmcs[RMCS_ES], ax

                ;DPMI Simulate Real Mode Interrupt (INT 31h AX=0300h)
                ;BL = interrupt number (4Bh), BH = 0, CX = 0 (no stack words)
                ;ES:EDI = pointer to real-mode call structure
                push    es
                push    ds
                pop     es                  ;ES = DS (flat selector)
                mov     edi, OFFSET vds_rmcs
                mov     bl, 4Bh
                xor     bh, bh
                xor     ecx, ecx
                mov     ax, 0300h
                int     31h
                pop     es
                jc      __pg_fail

                ;Check real-mode Carry Flag in returned FLAGS
                test    WORD PTR vds_rmcs[RMCS_FLAGS], 1
                jnz     __pg_fail

                ;Read physical address and buffer ID from DDS
                mov     ebx, vds_dds_lin
                mov     eax, DWORD PTR [ebx + DDS_PHYS]
                movzx   edx, WORD PTR [ebx + DDS_BUFID]
                jmp     __pg_ok

                ;--- Common success/failure paths ---
__pg_ok:
IFDEF DEBUG_SERIAL
                push    eax
                push    esi
                mov     esi, OFFSET dbg_s_pa_arrow
                call    dbg_str
                call    dbg_hex32
                call    dbg_crlf
                pop     esi
                pop     eax
ENDIF
                pop     edi
                pop     esi
                pop     ecx
                pop     ebx
                clc
                ret

__pg_fail:
IFDEF DEBUG_SERIAL
                push    esi
                mov     esi, OFFSET dbg_s_pa_fail
                call    dbg_str
                pop     esi
ENDIF
                pop     edi
                pop     esi
                pop     ecx
                pop     ebx
                stc
                ret
physaddr_translate ENDP

;============================================================================
; physaddr_release_lock -- Release a physical address lock
;
; For PHYSADDR_VDS, calls VDS Unlock DMA Region (INT 4Bh AX=8104h).
; For all other methods, this is a no-op.
;
; Entry: EAX = linear address, ECX = region size, EDX = lock handle
; Exit:  None (errors ignored)
; Destroys: EAX
;
physaddr_release_lock PROC NEAR
                cmp     physaddr_method, PHYSADDR_VDS
                jne     __pr_done

                push    ebx
                push    ecx
                push    esi
                push    edi

                ;Fill DDS for VDS Unlock DMA Region (INT 4Bh AX=8104h)
                mov     ebx, vds_dds_lin
                mov     DWORD PTR [ebx + DDS_SIZE], ecx
                mov     DWORD PTR [ebx + DDS_LINEAR], eax
                mov     WORD PTR [ebx + DDS_SEG], 0
                mov     WORD PTR [ebx + DDS_BUFID], dx

                ;Zero and fill RMCS
                push    eax
                push    ecx
                mov     edi, OFFSET vds_rmcs
                mov     ecx, RMCS_ALLOC / 4
                xor     eax, eax
                rep     stosd
                pop     ecx
                pop     eax

                mov     DWORD PTR vds_rmcs[RMCS_EAX], 8104h
                mov     ax, vds_dds_seg
                mov     WORD PTR vds_rmcs[RMCS_ES], ax

                ;DPMI Simulate Real Mode Interrupt
                push    es
                push    ds
                pop     es
                mov     edi, OFFSET vds_rmcs
                mov     bl, 4Bh
                xor     bh, bh
                xor     ecx, ecx
                mov     ax, 0300h
                int     31h
                pop     es
                ;Ignore all errors on unlock

                pop     edi
                pop     esi
                pop     ecx
                pop     ebx

__pr_done:      ret
physaddr_release_lock ENDP

;============================================================================
; physaddr_shutdown -- Free internal resources
;
; For PHYSADDR_RING0, unmaps the page directory and cached page table.
; For PHYSADDR_VDS, frees the conventional memory DDS block.
;
; Entry: None (call from shutdown_driver)
; Exit:  physaddr_method reset to 0
; Destroys: EAX, EDX
;
physaddr_shutdown PROC NEAR
                push    ebx
                push    ecx

                cmp     physaddr_method, PHYSADDR_RING0
                je      __ps_ring0
                cmp     physaddr_method, PHYSADDR_VDS
                je      __ps_vds
                jmp     __ps_done

__ps_ring0:     ;Unmap cached page table if any
                cmp     r0_ptab_lin, 0
                je      __ps_pdir

                mov     ecx, r0_ptab_lin
                mov     ebx, ecx
                shr     ebx, 16
                and     ecx, 0FFFFh
                mov     ax, 0801h           ;DPMI Free Physical Address Mapping
                int     31h
                mov     r0_ptab_lin, 0
                mov     r0_ptab_phys, 0

__ps_pdir:      ;Unmap page directory
                cmp     r0_pdir_lin, 0
                je      __ps_done

                mov     ecx, r0_pdir_lin
                mov     ebx, ecx
                shr     ebx, 16
                and     ecx, 0FFFFh
                mov     ax, 0801h
                int     31h
                mov     r0_pdir_lin, 0
                mov     r0_pdir_phys, 0
                jmp     __ps_done

__ps_vds:       ;Free DDS conventional memory block
                ;DPMI Free DOS Memory Block (INT 31h AX=0101h), DX = selector
                cmp     vds_dds_lin, 0
                je      __ps_done

                mov     dx, vds_dds_sel
                mov     ax, 0101h
                int     31h
                mov     vds_dds_lin, 0
                mov     vds_dds_seg, 0
                mov     vds_dds_sel, 0

__ps_done:      mov     physaddr_method, 0

                pop     ecx
                pop     ebx
                ret
physaddr_shutdown ENDP

ENDIF ; PHYSADDR_ASM_INCLUDED
