; SPDX-FileType: SOURCE
; SPDX-FileCopyrightText: Copyright (C) 2026 Volkert de Buisonjé
; SPDX-FileContributor: Generated by Claude (Anthropic), reviewed by Volkert de Buisonjé
; SPDX-License-Identifier: Apache-2.0
;
; PCM Format Conversion: up-convert to 16-bit signed stereo
;
; Converts 8-bit unsigned or 16-bit signed PCM data (mono or stereo) into
; 16-bit signed stereo. Sound devices like AC'97/ICHx require this format
; for DMA playback; this routine is kept separate from device-specific
; logic so that drivers for hardware that accepts other formats natively
; can bypass it entirely.
;
; Prerequisites: The including file must define the following variables
; before this file is included. The routine takes a buffer index in EBX
; and indexes into these arrays; the caller must ensure they are large
; enough for all indices used.
;
;   buff_data     dd N dup (?)   ; linear address of source PCM data
;   buff_len      dd N dup (?)   ; source data length in bytes
;   buff_pack     dd N dup (?)   ; pack_type (bit 7 = stereo, bits 0-2 = format)
;   stg_addr      dd N dup (0)   ; linear address of destination staging buffer
;   stg_samples   dd N dup (0)   ; output: number of 16-bit samples in staging buffer

IFNDEF TO16S_ASM_INCLUDED
TO16S_ASM_INCLUDED EQU 1

;----------------------------------------------------------------------------
; convert_to_16stereo -- Convert PCM data to 16-bit signed stereo
;
; Reads from the application's buffer and writes the converted data into
; the staging buffer. Handles 8-bit unsigned mono/stereo and 16-bit
; mono/stereo based on pack_type.
;
; Entry: EBX = buffer index
;        buff_data[ebx], buff_len[ebx], buff_pack[ebx] must be set
;        stg_addr[ebx] must point to a sufficiently large staging buffer
; Exit:  stg_samples[ebx] = number of 16-bit samples written
;        Staging buffer filled with converted data
; Destroys: EAX, ECX, EDX, ESI, EDI
;
convert_to_16stereo PROC NEAR
                push    ebx

                mov     esi, buff_data[ebx*4]   ;source pointer
                mov     edi, stg_addr[ebx*4]    ;destination pointer
                mov     ecx, buff_len[ebx*4]    ;source byte count
                mov     edx, buff_pack[ebx*4]   ;pack_type

                test    edx, 80h                ;bit 7 = stereo flag
                jnz     __stereo

                ;--- Mono input ---
                and     edx, 7Fh                ;isolate packing bits
                cmp     edx, 4
                je      __mono_16bit

                ;8-bit unsigned mono -> 16-bit signed stereo (4x expansion)
                ;Each input byte produces a 32-bit L+R output pair
__mono_8bit:    or      ecx, ecx
                jz      __done
@@:             movzx   eax, BYTE PTR [esi]     ;read 8-bit unsigned sample
                inc     esi
                xor     al, 80h                 ;unsigned -> signed
                shl     eax, 8                  ;scale to 16-bit (in AX)
                mov     edx, eax                ;duplicate for stereo
                shl     edx, 16                 ;EDX = right channel in high word
                or      eax, edx                ;EAX = [R_hi R_lo L_hi L_lo]
                mov     [edi], eax              ;write L+R pair
                add     edi, 4
                dec     ecx
                jnz     @b

                ;Each input byte produces 4 output bytes (2 x 16-bit samples).
                ;BDL length field counts 16-bit samples (bytes / 2).
                mov     ecx, buff_len[ebx*4]
                shl     ecx, 1                  ;input_bytes * 2 = 16-bit sample count
                mov     stg_samples[ebx*4], ecx
                jmp     __done

                ;16-bit mono -> 16-bit signed stereo (2x expansion)
__mono_16bit:   shr     ecx, 1                  ;byte count -> sample count
                or      ecx, ecx
                jz      __done
@@:             movzx   eax, WORD PTR [esi]     ;read 16-bit sample
                add     esi, 2
                mov     edx, eax
                shl     edx, 16
                or      eax, edx                ;duplicate L -> R
                mov     [edi], eax
                add     edi, 4
                dec     ecx
                jnz     @b

                ;Each 16-bit input sample produces 4 output bytes (2 x 16-bit samples).
                ;BDL length field counts 16-bit samples (bytes / 2).
                ;input_bytes / 2 (mono samples) * 2 (L+R) = input_bytes.
                mov     ecx, buff_len[ebx*4]    ;16-bit sample count = input bytes
                mov     stg_samples[ebx*4], ecx
                jmp     __done

__stereo:       and     edx, 7Fh
                cmp     edx, 4
                je      __stereo_16bit

                ;8-bit unsigned stereo -> 16-bit signed stereo (2x expansion)
                ;Input: L,R,L,R... bytes; Output: L16,R16,L16,R16... words
__stereo_8bit:  shr     ecx, 1                  ;byte pairs
                or      ecx, ecx
                jz      __done
@@:             movzx   eax, BYTE PTR [esi]     ;left channel
                xor     al, 80h
                shl     eax, 8
                movzx   edx, BYTE PTR [esi+1]   ;right channel
                xor     dl, 80h
                shl     edx, 8
                and     eax, 0FFFFh
                shl     edx, 16
                or      eax, edx                ;EAX = [R16 L16]
                mov     [edi], eax
                add     esi, 2
                add     edi, 4
                dec     ecx
                jnz     @b

                ;Each input L,R byte pair produces 4 output bytes (2 x 16-bit samples).
                ;BDL length field counts 16-bit samples (bytes / 2).
                ;input_bytes / 2 (pairs) * 2 (16-bit L+R) = input_bytes.
                mov     ecx, buff_len[ebx*4]    ;16-bit sample count = input bytes
                mov     stg_samples[ebx*4], ecx
                jmp     __done

                ;16-bit stereo -> 16-bit stereo (1x, just copy)
__stereo_16bit: mov     eax, ecx
                shr     ecx, 2                  ;dword count for fast copy
                rep     movsd
                mov     ecx, eax
                and     ecx, 3                  ;remaining bytes
                rep     movsb

                ;BDL length field counts 16-bit samples (bytes / 2).
                mov     ecx, buff_len[ebx*4]
                shr     ecx, 1                  ;byte count / 2 = 16-bit sample count
                mov     stg_samples[ebx*4], ecx

__done:         pop     ebx
                ret
convert_to_16stereo ENDP

ENDIF ; TO16S_ASM_INCLUDED
