; SPDX-FileType: SOURCE
; SPDX-FileCopyrightText: Copyright (C) 1991-1993 Miles Design, Inc.
; SPDX-FileCopyrightText: Copyright (C) 2026 Volkert de Buisonje
; SPDX-FileContributor: Generated by Claude (Anthropic), reviewed by Volkert de Buisonje
; SPDX-License-Identifier: Apache-2.0
;
; VOC File Playback: Creative Voice File block parser and playback controller
;
; Adapted from dmasnd32.asm (AIL/32 by John Miles / Miles Design, Inc.)
; for use in new AIL/32 driver implementations.
;
; This module is hardware-agnostic: it contains zero references to I/O ports,
; DMA engines, PCI, or codec registers. All procedures operate exclusively
; on in-memory VOC data structures. The driver decides when to call
; voc_fetch_block and what to do with the result (feed it through register_sb
; for a polled driver, or program DMA directly for an IRQ-driven driver).
;
; API Contract:
; - Driver must call voc_shutdown() during driver shutdown
; - Driver must call voc_shutdown() when cancelling VOC playback
; - voc_fetch_block() maintains internal state between calls
; - All state is automatically reset by play_VOC_file()
;
; Debug Note: If playback starts at wrong position, check:
; - voc_cur_block_off initialization in play_VOC_file
; - voc_cur_block_len updates in voc_fetch_block
; - Buffer size limits (07FFEh bytes max chunk for 16-bit BDL length)
;
; Prerequisites (must be defined before including this file):
;
;   sbuffer STRUC              ; sound buffer structure with these fields:
;     s_pack_type   dd ?       ;   packing type
;     s_sample_rate dd ?       ;   sample rate (SB time constant byte)
;     s_ptr_data    dd ?       ;   protected-mode pointer (offset)
;     s_sel_data    dw ?       ;   protected-mode pointer (selector)
;     s_seg_data    dd ?       ;   real-mode segment pointer
;     s_len         dd ?       ;   data length in bytes
;   sbuffer ENDS
;
;   buffer_mode   dd ?         ; current mode (VOC_MODE or BUF_MODE)
;   DAC_status    dd ?         ; playback state (DAC_STOPPED/PAUSED/PLAYING/DONE)
;   VOC_MODE      equ 0       ; Creative Voice File playback mode
;   BUF_MODE      equ 1       ; Dual-buffer DMA playback mode
;   DAC_STOPPED   equ 0
;   DAC_DONE      equ 3
;   stop_d_pb     PROC         ; driver's stop procedure (called by play_VOC_file)
;   ADD_PTR       MACRO        ; real-mode segment pointer arithmetic

IFNDEF VOC_ASM_INCLUDED
VOC_ASM_INCLUDED EQU 1

;----------------------------------------------------------------------------
; Private state variables for VOC block chain traversal
;----------------------------------------------------------------------------

voc_seg_ptr     dd ?            ;real-mode segment:offset (parallel tracking)

voc_blk_ptr     LABEL FAR PTR  ;48-bit far pointer for LES loading
voc_blk_off     dd ?            ;protected-mode offset into VOC data
voc_blk_sel     dd ?            ;protected-mode selector

voc_xblk_status dd ?            ;extended block (type 8) override flag
voc_xblk_tc     dd ?            ;extended block time constant
voc_xblk_pack   dd ?            ;extended block pack type

voc_loop_off    dd ?            ;repeat loop: saved block offset
voc_loop_seg    dd ?            ;repeat loop: saved seg_ptr
voc_loop_cnt    dd ?            ;repeat loop: iterations (-1 = infinite)

voc_cur_rate    dd ?            ;sample rate TC from last type 1 block
voc_cur_pack    dd ?            ;pack type from last type 1 block

voc_cur_block_off dd ?          ;current offset within current voice block
voc_cur_block_len dd ?          ;remaining length in current voice block
; voc_cur_block_ptr and voc_cur_block_sel not needed - use voc_blk_ptr/voc_seg_ptr

voc_sbuf        sbuffer <>      ;filled by voc_fetch_block for driver to consume

;----------------------------------------------------------------------------
; voc_block_type -- Return the type byte of the current VOC block
;
; Entry: voc_blk_off/voc_blk_sel set to current block
; Exit:  EAX = block type (0-255)
; Destroys: ESI (restored by USES)
;----------------------------------------------------------------------------
voc_block_type  PROC USES ebx esi edi es

                les esi, voc_blk_ptr    ;load protected-mode far pointer
                mov eax, 0
                mov al, es:[esi]        ;first byte = block type

                ret
voc_block_type  ENDP

;----------------------------------------------------------------------------
; voc_set_xblk -- Capture extended block (type 8) overrides
;
; If the current block is type 8 (extended), saves the time constant and
; pack type for the next voice block (type 1) to use instead of its own
; header values. Sets voc_xblk_status=1 to flag the override.
;
; Entry: voc_blk_off/voc_blk_sel set to current block
; Exit:  voc_xblk_status, voc_xblk_tc, voc_xblk_pack updated if type 8
; Destroys: EAX, ESI (restored by USES)
;----------------------------------------------------------------------------
voc_set_xblk    PROC USES ebx esi edi es

                les esi, voc_blk_ptr
                cmp BYTE PTR es:[esi], 8
                jne __exit              ;not an extended block, do nothing

                mov eax, 0

                mov al, es:[esi+5]      ;high byte of time constant
                mov voc_xblk_tc, eax    ;normal sample rate TC

                mov ax, es:[esi+6]      ;AL = pack type, AH = mode (0=mono, 1=stereo)
                cmp ah, 1              ;stereo?
                jne __set_pack

                or al, 80h             ;yes, set stereo flag in pack byte

__set_pack:     and eax, 0FFh
                mov voc_xblk_pack, eax

                mov voc_xblk_status, 1  ;flag extended block override
__exit:
                ret
voc_set_xblk    ENDP

;----------------------------------------------------------------------------
; voc_marker_num -- Return the marker number of the current block
;
; Entry: voc_blk_off/voc_blk_sel set to current block
; Exit:  EAX = marker number if type 4, or -1 if not a marker block
; Destroys: ESI (restored by USES)
;----------------------------------------------------------------------------
voc_marker_num  PROC USES ebx esi edi es

                les esi, voc_blk_ptr    ;load pointer to current block
                cmp BYTE PTR es:[esi], 4
                mov eax, -1
                jne __exit              ;not a marker block, return -1

                mov eax, 0              ;return marker number (16-bit value)
                mov ax, WORD PTR es:[esi+4]
__exit:
                ret
voc_marker_num  ENDP

;----------------------------------------------------------------------------
; voc_next_block -- Advance block pointers to the next VOC block
;
; Reads the 24-bit block length from bytes 1-3 of the current block,
; adds 4 (type byte + 3 length bytes) to get the offset to the next block,
; then advances both the protected-mode (voc_blk_off) and real-mode
; (voc_seg_ptr) pointers.
;
; Entry: voc_blk_off/voc_blk_sel/voc_seg_ptr set to current block
; Exit:  All three pointers advanced to the next block
; Destroys: EAX, EDX, ESI, EDI (restored by USES)
;----------------------------------------------------------------------------
voc_next_block  PROC USES ebx esi edi es

                les esi, voc_blk_ptr

                mov eax, es:[esi+1]     ;read 24-bit block length (bytes 1-3)
                and eax, 0FFFFFFh
                add eax, 4              ;add type byte + 3 length bytes

                add esi, eax            ;advance protected-mode offset
                mov voc_blk_off, esi

                mov si, WORD PTR voc_seg_ptr
                mov di, WORD PTR voc_seg_ptr+2

                shld edx, eax, 16       ;EDX:AX = 32-bit offset for ADD_PTR
                ADD_PTR ax, dx, di, si  ;advance real-mode seg:off pointer

                mov WORD PTR voc_seg_ptr, si
                mov WORD PTR voc_seg_ptr+2, di
                ret
voc_next_block  ENDP

;----------------------------------------------------------------------------
; voc_fetch_block -- Fetch the next playable voice block from the VOC chain
;
; Walks the VOC block chain starting at the current position, handling
; control blocks (repeat, extended, silence, marker) internally, and
; returns when a voice data block (type 1 or 2) is found.
;
; The result is written into voc_sbuf (an sbuffer structure) with the
; sample rate, pack type, data pointer, and length filled in. The driver
; then feeds voc_sbuf through its own register_sb / DMA path.
;
; Entry: voc_blk_off/voc_blk_sel/voc_seg_ptr set to current block
; Exit:  CF=0: voice block found, voc_sbuf filled, pointers advanced past it
;        CF=1: end of data (terminator or marker reached)
; Destroys: EAX, EBX, ECX, EDX, ESI, EDI
;----------------------------------------------------------------------------
voc_fetch_block PROC USES es

                ;Check if we have remaining data in the current block
                cmp voc_cur_block_len, 0
                jg __use_remaining

__do_block:     call voc_block_type
IFDEF DEBUG_SERIAL
                ; Debug: block type
                push eax
                mov esi, OFFSET dbg_s_voc_fetch
                call dbg_str
                mov eax, [esp]
                call dbg_hex8
                cmp eax, 1
                je __dbg_new
                cmp eax, 2
                je __dbg_cont
                jmp __dbg_done
__dbg_new:      mov esi, OFFSET dbg_s_voc_new
                jmp __dbg_print
__dbg_cont:     mov esi, OFFSET dbg_s_voc_cont
__dbg_print:     call dbg_str
__dbg_done:     call dbg_crlf
                pop eax
                jmp __do_block_continue
__do_block_continue:
ENDIF ; DEBUG_SERIAL
                cmp eax, 0              ;type 0: terminator
                je __terminate
                cmp eax, 1              ;type 1: new voice data block
                je __new_voice
                cmp eax, 2              ;type 2: continued voice data block
                je __cont_voice
                cmp eax, 3              ;type 3: silence period
                je __skip_block         ;skip (matches PAS/Ad Lib Gold behavior)
                cmp eax, 4              ;type 4: marker (end of section)
                je __terminate
                cmp eax, 6              ;type 6: beginning of repeat loop
                je __rept_loop
                cmp eax, 7              ;type 7: end of repeat loop
                je __end_loop
                cmp eax, 8              ;type 8: extended block
                je __extended
                jmp __skip_block        ;unrecognized block type, skip it

__use_remaining:
                ;We have remaining data in the current block - use it
                ;voc_blk_ptr already points to the current block header
                ;voc_cur_block_off tracks our position within the block
                ;(includes header size, so blk_off + cur_block_off = data ptr)
                les esi, voc_blk_ptr    ;load selector into ES

IFDEF DEBUG_SERIAL
                ; Debug: Using remaining block data
                push eax
                mov esi, OFFSET dbg_s_voc_remaining
                call dbg_str
                mov eax, voc_cur_block_off
                call dbg_hex32
                mov esi, OFFSET dbg_s_voc_length
                call dbg_str
                mov eax, voc_cur_block_len
                call dbg_hex32
                call dbg_crlf
                pop eax
ENDIF ; DEBUG_SERIAL

                ;Set sample rate and pack type from current block
                mov ebx, voc_cur_rate
                mov voc_sbuf.s_sample_rate, ebx
                mov ebx, voc_cur_pack
                mov voc_sbuf.s_pack_type, ebx

                ;Protected-mode pointer: block data start + current offset
                mov ebx, voc_blk_off
                add ebx, voc_cur_block_off
                mov voc_sbuf.s_ptr_data, ebx
                mov voc_sbuf.s_sel_data, es

                ;Real-mode pointer: voc_seg_ptr + current offset
                mov si, WORD PTR voc_seg_ptr
                mov di, WORD PTR voc_seg_ptr+2
                mov eax, voc_cur_block_off
                xor edx, edx
                shld edx, eax, 16
                ADD_PTR ax, dx, di, si
                mov WORD PTR voc_sbuf.s_seg_data, si
                mov WORD PTR voc_sbuf.s_seg_data+2, di

                ;Return remaining data (limit chunk size so worst-case 8-bit
                ;mono 4x expansion produces stg_samples <= 0xFFFF, fitting
                ;the 16-bit BDL length field)
                mov eax, voc_cur_block_len
                cmp eax, 07FFEh         ;32766 bytes -> max 65532 stg_samples
                jbe __use_remaining_size_ok
                mov eax, 07FFEh
__use_remaining_size_ok:
                mov voc_sbuf.s_len, eax

                ;Advance position within block
                add voc_cur_block_off, eax
                sub voc_cur_block_len, eax
                jnz __use_remaining_more

                call voc_next_block     ;block fully consumed, advance to next

__use_remaining_more:
                clc                     ;CF=0: voice block found
                jmp __exit

__extended:     call voc_set_xblk       ;capture time constant/pack overrides
                jmp __skip_block

__terminate:    stc                     ;CF=1: end of data
                jmp __exit

__skip_block:   call voc_next_block     ;advance to next block
                jmp __do_block          ;and try again

__rept_loop:    les esi, voc_blk_ptr
                movsx eax, WORD PTR es:[esi+4]  ;repeat count (-1 = infinite)
                mov voc_loop_cnt, eax

                call voc_next_block     ;advance past repeat-begin block

                mov eax, voc_seg_ptr    ;save loop return position
                mov voc_loop_seg, eax
                mov eax, voc_blk_off
                mov voc_loop_off, eax
                jmp __do_block

__end_loop:     cmp voc_loop_cnt, 0     ;loop counter exhausted?
                je __skip_block         ;yes, skip past end-loop block

                mov eax, voc_loop_off   ;jump back to loop start
                mov voc_blk_off, eax
                mov eax, voc_loop_seg
                mov voc_seg_ptr, eax

                cmp voc_loop_cnt, -1    ;infinite loop?
                je __do_block           ;yes, do not decrement
                dec voc_loop_cnt
                jmp __do_block

                ;--- Type 2: continued voice block ---
                ;Uses saved rate/pack from the most recent type 1 block.
__cont_voice:   les esi, voc_blk_ptr
                mov eax, es:[esi+1]     ;24-bit block length
                and eax, 0FFFFFFh

                ;Store current block info for partial consumption
                mov voc_cur_block_off, 4  ;offset to data (type + 3 len bytes)
                mov voc_cur_block_len, eax ;full block length

                ;Fill voc_sbuf with saved rate/pack and block data pointer
                mov ebx, voc_cur_rate
                mov voc_sbuf.s_sample_rate, ebx
                mov ebx, voc_cur_pack
                mov voc_sbuf.s_pack_type, ebx

                ;Protected-mode pointer: block start + current offset
                mov ebx, voc_blk_off
                add ebx, voc_cur_block_off
                mov voc_sbuf.s_ptr_data, ebx
                mov voc_sbuf.s_sel_data, es

                ;Real-mode pointer calculation
                mov si, WORD PTR voc_seg_ptr
                mov di, WORD PTR voc_seg_ptr+2
                mov eax, voc_cur_block_off
                xor edx, edx
                shld edx, eax, 16
                ADD_PTR ax, dx, di, si
                mov WORD PTR voc_sbuf.s_seg_data, si
                mov WORD PTR voc_sbuf.s_seg_data+2, di

                ;Limit chunk size (see __use_remaining comment)
                mov eax, voc_cur_block_len
                cmp eax, 07FFEh         ;32766 bytes -> max 65532 stg_samples
                jbe __new_voice_size_ok
                mov eax, 07FFEh
__new_voice_size_ok:
                mov voc_sbuf.s_len, eax

                ;Advance position within block
                add voc_cur_block_off, eax
                sub voc_cur_block_len, eax
                jz __cont_voice_done  ;if block fully consumed, advance to next

                clc                     ;CF=0: voice block found (more data remains)
                jmp __exit

__cont_voice_done:
                call voc_next_block     ;advance past this block
                clc                     ;CF=0: voice block found
                jmp __exit

                ;--- Type 1: new voice data block ---
                ;Parses time constant (TC) and pack type from the block header.
                ;If a preceding type 8 (extended) block set overrides, those
                ;values are used instead.
__new_voice:    les esi, voc_blk_ptr
                mov eax, 0
                mov ebx, 0
                mov bl, es:[esi+4]      ;BL = time constant (TC)
                mov al, es:[esi+5]      ;AL = packing type

                cmp voc_xblk_status, 0  ;extended block override active?
                je __use_vd             ;no, use voice data block values
                mov eax, voc_xblk_pack  ;yes, use extended block overrides
                mov ebx, voc_xblk_tc
                mov voc_xblk_status, 0  ;clear override for next block

__use_vd:       mov voc_cur_rate, ebx   ;save for type 2 (continued) blocks
                mov voc_cur_pack, eax
                mov ecx, eax            ; Preserve pack type before ECX gets overwritten

                les esi, voc_blk_ptr
                mov eax, es:[esi+1]     ;24-bit block length
                and eax, 0FFFFFFh
                sub eax, 2              ;subtract TC + pack bytes = voice data length

                ;Store current block info for partial consumption
                mov voc_cur_block_off, 6  ;offset to data (type + 3 len + TC + pack)
                mov voc_cur_block_len, eax ;voice data length

                mov voc_sbuf.s_sample_rate, ebx
                mov voc_sbuf.s_pack_type, ecx  ;ECX still has the pack type from AL

                ;Protected-mode pointer: block start + current offset
                mov ebx, voc_blk_off
                add ebx, voc_cur_block_off
                mov voc_sbuf.s_ptr_data, ebx
                mov voc_sbuf.s_sel_data, es

                ;Real-mode pointer calculation
                mov si, WORD PTR voc_seg_ptr
                mov di, WORD PTR voc_seg_ptr+2
                mov eax, voc_cur_block_off
                xor edx, edx
                shld edx, eax, 16
                ADD_PTR ax, dx, di, si
                mov WORD PTR voc_sbuf.s_seg_data, si
                mov WORD PTR voc_sbuf.s_seg_data+2, di

                ;Limit chunk size (see __use_remaining comment)
                mov eax, voc_cur_block_len
                cmp eax, 07FFEh         ;32766 bytes -> max 65532 stg_samples
                jbe __new_voice_chunk_size_ok
                mov eax, 07FFEh
__new_voice_chunk_size_ok:
                mov voc_sbuf.s_len, eax

                ;Advance position within block
                add voc_cur_block_off, eax
                sub voc_cur_block_len, eax
                jz __new_voice_done  ;if block fully consumed, advance to next

                clc                     ;CF=0: voice block found (more data remains)
                jmp __exit

__new_voice_done:
                call voc_next_block     ;advance past this block
                clc                     ;CF=0: voice block found
                jmp __exit

__exit:
                ret
voc_fetch_block ENDP

;****************************************************************************
; play_VOC_file -- Start playback of a Creative Voice File
;
; API function ID: AIL_P_VOC_FILE (123)
;
; Parses the VOC file header to find the data block offset, then sets up
; the block chain pointers. If Block is -1, playback starts from the first
; voice block. Otherwise, the chain is walked to find the specified marker
; number, and playback starts from the voice block following that marker.
;
; Actual DMA output is initiated by start_d_pb (called by the application
; or internally by the API after this returns). The driver's serve_driver
; polls voc_fetch_block to chain through subsequent blocks.
;
; Entry: H       = driver handle (unused)
;        VOCFile = far pointer to VOC file data in memory
;        VOCSeg  = real-mode segment pointer to VOC file data
;        Block   = marker number to start from, or -1 for first block
; Exit:  DAC_status = DAC_STOPPED if block found, DAC_DONE if not
;****************************************************************************
play_VOC_file   PROC USES ebx esi edi es,\
                H, VOCFile:FAR PTR, VOCSeg, Block

                pushfd
                cli
                cld

IFDEF DEBUG_SERIAL
                ; Debug: play_VOC_file called
                mov esi, OFFSET dbg_s_voc_play
                call dbg_str
                call dbg_crlf
ENDIF ; DEBUG_SERIAL

                mov voc_xblk_status, 0
                mov voc_cur_block_len, 0  ;no current block initially
                mov voc_cur_block_off, 0  ;ensure clean position tracking
                mov voc_cur_rate, 0      ;initialize to safe default
                mov voc_cur_pack, 0      ;initialize to safe default

                les esi, [VOCFile]
                movzx eax, WORD PTR es:[esi+14h]  ;data block offset from VOC header

                add esi, eax
                mov voc_blk_off, esi    ;protected-mode offset to first data block
                mov voc_blk_sel, es

                mov si, WORD PTR [VOCSeg]
                mov di, WORD PTR [VOCSeg]+2

                ADD_PTR ax, 0, di, si   ;DI:SI -> real-mode pointer to first data block
                mov WORD PTR voc_seg_ptr, si
                mov WORD PTR voc_seg_ptr+2, di

                call stop_d_pb        ;stop any current playback
                mov buffer_mode, VOC_MODE
                mov DAC_status, DAC_DONE

                les esi, [VOCFile]      ;restore ES for block chain walking

                cmp [Block], -1         ;play first block if no marker specified
                je __do_it

                ;Walk the block chain looking for the specified marker number
__find_blk:     call voc_block_type
                cmp eax, 0              ;terminator block?
                je __exit               ;yes, exit (marker not found, DAC_DONE)
                call voc_set_xblk       ;capture extended block overrides
                call voc_marker_num     ;EAX = marker # or -1 if not a marker
                mov esi, eax
                call voc_next_block     ;advance to next block
                cmp esi, [Block]
                jne __find_blk

__do_it:        mov DAC_status, DAC_STOPPED

__exit:         POP_F
                ret
play_VOC_file   ENDP

;****************************************************************************
; index_VOC_blk -- Index a specific block in a Creative Voice File
;
; API function ID: AIL_INDEX_VOC_BLK (120)
;
; Self-contained: uses LOCAL variables, does not modify the play_VOC_file
; block chain state. Walks the VOC file from the beginning to find the
; voice data block following the specified marker, and fills the caller's
; sbuffer structure with the block's parameters.
;
; Entry: H       = driver handle (unused)
;        VOCFile = far pointer to VOC file data in memory
;        VOCSeg  = real-mode segment pointer to VOC file data
;        Block   = marker number to search for, or -1 for first voice block
;        SBuf    = pointer to sbuffer structure to fill
; Exit:  EAX = 1 if voice block found (sbuffer filled), 0 if not found
;****************************************************************************
index_VOC_blk   PROC USES ebx esi edi es,\
                H, VOCFile:FAR PTR, VOCSeg, Block, SBuf
                LOCAL idx_off
                LOCAL idx_seg
                LOCAL x_status
                LOCAL x_pack:BYTE
                LOCAL x_tc:BYTE

                ASSUME edi:PTR sbuffer

                pushfd
                cli
                cld

                mov x_status, 0

                les esi, [VOCFile]
                movzx eax, WORD PTR es:[esi+14h]  ;data block offset from VOC header

                add esi, eax
                mov idx_off, esi        ;protected-mode offset to first data block

                mov esi, [VOCSeg]       ;real-mode segment pointer to data block
                add esi, eax
                mov idx_seg, esi

                mov ebx, [Block]

                ;Walk the block chain looking for the target voice block
__get_type:     mov esi, idx_off
                mov eax, 0
                mov al, es:[esi]        ;block type byte
                cmp eax, 0              ;terminator?
                je __exit               ;yes, return EAX=0 (block not found)

                cmp eax, 8             ;extended block?
                jne __chk_voice

                ;Type 8: extended block -- capture overrides
                mov al, es:[esi+5]      ;high byte of time constant
                mov x_tc, al
                mov ax, es:[esi+6]      ;AL = pack, AH = mode (0=mono, 1=stereo)
                cmp ah, 1
                jne __set_pack
                or al, 80h             ;set stereo flag
__set_pack:     mov x_pack, al
                mov x_status, 1
                jmp __next_blk

__chk_voice:    cmp eax, 1             ;voice data block?
                jne __chk_marker

                cmp ebx, -1            ;marker found (or searching from start)?
                je __vblk_found         ;yes, use this voice data block
                jmp __next_blk          ;no, keep looking

__chk_marker:   cmp eax, 4             ;marker block?
                jne __next_blk

                cmp bx, es:[esi+4]      ;compare marker numbers
                jne __next_blk

                mov ebx, -1            ;marker found, use next voice block

                ;Advance to the next block
__next_blk:     mov esi, idx_off
                mov eax, es:[esi+1]
                and eax, 0FFFFFFh       ;24-bit block length
                add eax, 4              ;offset to next block
                add esi, eax
                mov idx_off, esi        ;advance protected-mode pointer

                mov si, WORD PTR idx_seg
                mov di, WORD PTR idx_seg+2
                shld edx, eax, 16
                ADD_PTR ax, dx, di, si  ;advance real-mode segment pointer
                mov WORD PTR idx_seg, si
                mov WORD PTR idx_seg+2, di
                jmp __get_type

                ;Voice block found -- fill the caller's sbuffer
__vblk_found:   mov edi, [SBuf]
                mov esi, idx_off

                mov eax, 0
                mov ebx, 0
                mov bl, es:[esi+4]      ;BL = time constant (TC)
                mov al, es:[esi+5]      ;AL = packing type

                cmp x_status, 0         ;extended block override active?
                je __use_vd
                mov al, x_pack          ;use extended block values
                mov bl, x_tc
                mov x_status, 0

__use_vd:       mov [edi].s_sample_rate, ebx
                mov [edi].s_pack_type, eax

                mov esi, idx_off
                mov eax, es:[esi+1]
                and eax, 0FFFFFFh       ;24-bit block length
                sub eax, 2              ;subtract TC + pack bytes = voice data length
                mov [edi].s_len, eax

                mov esi, idx_off
                add esi, 6              ;skip type + len + TC + pack
                mov [edi].s_ptr_data, esi
                mov [edi].s_sel_data, es

                mov ax, WORD PTR idx_seg
                mov dx, WORD PTR idx_seg+2
                ADD_PTR 6, 0, dx, ax    ;advance real-mode pointer by 6
                mov WORD PTR [edi].s_seg_data, ax
                mov WORD PTR [edi].s_seg_data+2, dx

                ASSUME edi:NOTHING

                mov eax, 1              ;return 1 = block found

__exit:         POP_F
                ret
index_VOC_blk   ENDP

;----------------------------------------------------------------------------
; voc_shutdown -- Reset VOC module state
;
; Should be called by the driver during shutdown to ensure clean state.
; Resets all VOC block tracking variables to prevent state pollution.
;
; Entry: None
; Exit:  All VOC module state variables reset to initial values
; Destroys: None
;----------------------------------------------------------------------------
voc_shutdown    PROC
                mov voc_xblk_status, 0
                mov voc_cur_block_len, 0  ;reset block tracking
                mov voc_cur_block_off, 0
                ret
voc_shutdown    ENDP

; Make VOC functions available to the driver
PUBLIC play_VOC_file
PUBLIC index_VOC_blk
PUBLIC voc_fetch_block
PUBLIC voc_shutdown

; Debug strings (when DEBUG_SERIAL is defined)
IFDEF DEBUG_SERIAL
dbg_s_voc_remaining db 'VOC: remaining off:',0
dbg_s_voc_length   db ' len:',0
dbg_s_voc_fetch    db 'VOC: fetch block type:',0
dbg_s_voc_new      db ' new',0
dbg_s_voc_cont     db ' cont',0
dbg_s_voc_done     db ' done',0
dbg_s_voc_play     db 'VOC: play_VOC_file called',0
ENDIF ; DEBUG_SERIAL

ENDIF ; VOC_ASM_INCLUDED
